homework 4 done - dictionary
eugene-okulik/userafimau pull request #3
Opened 2024-05-31 12:45 UTC by userafimau

2024-06-01 11:37 UTC, eugene-okulik requested changes
Всё отлично, но одну проверочку на внимательность не прошел ))

2024-06-01 11:37 UTC, eugene-okulik commented on homework/uladzimir_serafimau/homework_4/my_dictionary.py
> +my_dict['dict']['i am a tuple'] = 555
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-06-03 07:15 UTC, userafimau commented on homework/uladzimir_serafimau/homework_4/my_dictionary.py
> +my_dict['dict']['i am a tuple'] = 555
Исправил, добавил кортеж ключом.

2024-06-03 10:25 UTC, eugene-okulik approved these changes

2024-06-03 10:25 UTC, merged